config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :dashboard, only: [:new, :create, :destroy]

  resources :meetings, only: [:show]

  resources :journals do
    resources :tags, module: :journals
  end

  resources :photos, except: [:index, :new, :create] do
    resources :tags, module: :photos
  end

  resources :agendas, except: [:index] do
    resources :tags, module: :agendas
  end

  get '/tag_search', to: 'tags#search'

  get '/my_dashboard', to: 'dashboards#show'

  get '/my_calendar', to: 'meetings#index'
  get '/new_meeting', to: 'meetings#new'
  post '/new_meeting', to: 'meetings#create'

  get '/my_photos', to: 'photos#index'
  get '/new_photo', to: 'photos#new'
  post '/new_photo', to: 'photos#create'

  get '/my_agendas', to: 'agendas#index'

  root 'static_pages#home'
end

app/models/agenda.rb
class Agenda < ApplicationRecord
  belongs_to :user
  has_rich_text :body
  has_many :tags, as: :taggable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def clean_tags
    self.tags.map(&:name).reject(&:nil?)[0].split(", ")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end
  
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  belongs_to :user
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
  has_many :tags, as: :taggable

  validates :title, :body, presence: true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user

  validates :title, :description, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :tags, as: :taggable
  has_one_attached :image

  validates :image, :summary, presence: true
  validates :image, content_type: { in: %w[image/jpeg, image/jpg, image/gif, image/png],
                                    message: "Must be a valid image type" },
                                    size: { less_than: 10.megabytes, message: "Must be 10mb or smaller" }
  validates :summary, length: { maximum: 150 }

  def show_image
    image.variant(resize_to_limit: [200, 200])
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :taggable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :build_dashboard

  has_many :journals, dependent: :destroy
  has_many :meetings, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :agendas, dependent: :destroy
  has_one :dashboard, dependent: :destroy

  private

    def build_dashbaord
      Dashbaord.create(user_id: self.id)
    end
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  before_action :find_agenda, except: [:index, :new, :create]

  def index
    @agendas = current_user.agendas.all
  end

  def new
    @agenda = current_user.agendas.build
  end

  def create
    @agenda = current_user.agendas.build(agenda_params)

    if @agenda.save
      flash[:notice] = "New agenda saved!"
      redirect_to @agenda
    else
      flash[:notice] = "Something went wrong"
      render :new
    end
  end

  def edit
  end

  def update
    @agenda.update(agenda_params)
    redirect_to agendas_path
  end

  def destroy
    @agenda.destroy
    flash[:notice] = "Agenda deleted"
    redirect_to my_agendas_path
  end

  private

    def find_agenda
      @agenda = Agenda.find(params[:id])
    end

    def agenda_params
      params.require(:agenda).permit(:title, :body, :tags)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name])
    end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def new
    @dashboard = current_user.dashboard.build
  end

  def create
    @dashboard = current_user.dashboard.build(dashboard_params)
    if @dashboard.save
      redirect_to dashboard_path
    end
  end

  def show
    @journals = current_user.journals.all
  end

  def show
    @dashboard = current_user.dashboard
  end

  private

    def dashboard_params
      params.require(:dashboard).permit(:user_id)
    end

end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :find_journal, only: [:show, :edit, :update, :destroy]

  def index
    @journals = current_user.journals
  end

  def new
    @journal = current_user.journals.build
  end

  def create
    @journal = current_user.journals.build(journal_params)

    if @journal.save
      redirect_to @journal
      flash[:notice] = "Add tags to make this entry searchable!"
    else
      render 'new'
      flash[:notice] = "Something went wrong"
    end
  end


  def show
  end

  def edit
  end

  def update
    @journal.update(journal_params)
    redirect_to my_dashboard_path
  end


  def destroy
    @journal.destroy
    flash[:notice] = "Entry successfully deleted"
    redirect_to journals_path
  end

  private

    def find_journal
      @journal = Journal.find(params[:id])
    end

    def journal_params
      params.require(:journal).permit(:title, :body)
    end

    # def permitted_params
    #   params.require(:journal).permit(:title, :body, tags: [])
    # end
    #
    # def tags
    #   permitted_params.slice(:tags)
    # end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :find_meeting, only: [:show]

  def index
    @meetings = current_user.meetings
  end

  def new
    @meeting = current_user.meetings.build
  end

  def create
    @meeting = current_user.meetings.build(meeting_params)

    if @meeting.save
      flash[:notice] = "Event created!"
      redirect_to my_calendar_path
    else
      flash[:notice] = "Event not saved"
      redner :new
    end
  end

  def show
  end

  def destroy
    @meeting.destroy
    redirect_to my_calendar_path
  end

  private

   def meeting_params
     params.require(:meeting).permit(:title, :start_date, :description)
   end

   def find_meeting
     @meeting = Meeting.find(params[:id])
   end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :find_photo, except: [:index, :new, :create]

  def index
    @photos = current_user.photos
  end

  def new
    @photo = current_user.photos.build
  end

  def create
    @photo = current_user.photos.build(photo_params)
    @photo.image.attach(params[:photo][:image])

    if @photo.save
      flash[:notice] = "Add tags to make this entry searchable!"
      redirect_to @photo
    else
      flash[:notice] = "Something went wrong, please try again"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @photo.update(photo_params)
    redirect_to my_dashboard_path
  end

  def destroy
    @photo.destroy
    flash[:notice] = "Photo successfulyl removed"
    redirect_to my_photos_path
  end

  private

    def find_photo
      @photo = Photo.find(params[:id])
    end

    # def photo_params
    #   permitted_params.except(:tags)
    # end

    def photo_params
      params.require(:photo).permit(:title, :summary, :image, :tags)
    end

    # def tags
    #   permitted_params.slice(:tags)
    # end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home]
  def home
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def create
    @tag = @taggable.tags.new(tag_params)
    @tag.save
    redirect_to my_dashboard_path
    flash[:notice] = "Entry added!"
  end

  def search
    @results = Tag.all.includes(:taggable).select{ |x| x.name.include?(params[:tags][:tag]) }.map{ |x| x.taggable }
  end


  private

    def tag_params
      params.require(:tag).permit(:name)
    end

end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dashboards/show.html.erb
<h2 class="ui centered header">My Dashboard</h2>

<div class="ui stackable centered grid">
  <div class="ui four wide column">
    <!-- loop through all a users topicables and generate a card for each (current_user.topicables.each do) -->
    <div class="ui card">
      <div class="content">
        <div class="centered header"><%= link_to "My Journals", journals_path, entries: @journals %></div>
      </div>
      <div class="content blurb">
        See what you've written, you star author, you!
        Our thoughts are valuable and deserve to be written, if only for your own eyes.
        Get your ideas out there adn see them become manifest in the real world! And then come back to find them here,
        so they don't get lost out in the big, wide universe.
      </div>
    </div>
  </div>
  <div class="ui four wide column">
    <!-- loop through all a users topicables and generate a card for each (current_user.topicables.each do) -->
    <div class="ui card">
      <div class="content">
        <div class="centered header"><%= link_to "My Photos", my_photos_path %></div>
      </div>
      <div class="content blurb">
        What photos have you found recently? Did you take any cool photos of your own?
        Come see your blossoming photo gallery! Who knows, maybe you'll develop a talent for scrapbooking,
        or a knack for amateur photography! Either way, your creations or photo collection should live somewhere.
        Probably not here in the long run, but at least for now.
      </div>
    </div>
  </div>
  <div class="ui four wide column">
    <!-- loop through all a users topicables and generate a card for each (current_user.topicables.each do) -->
    <div class="ui card">
      <div class="content">
        <div class="centered header"><%= link_to "My To-Dos", my_agendas_path %></div>
      </div>
      <div class="content blurb">
        Who has time to find a new piece of paper or spin up a phone app when you're out and about, just dump your
        to-dos here instead! That is the point of this site, after all - to have one location to keep everything you're up to these days.
        And people are up to a lot these days! We really should take some time for ourselves in between...
      </div>
    </div>
  </div>
  <div class="ui four wide column">
    <!-- loop through all a users topicables and generate a card for each (current_user.topicables.each do) -->
    <div class="ui card">
      <div class="content">
        <div class="centered header"><%= link_to "My Calendar", my_calendar_path %></div>
      </div>
      <div class="content blurb">
        Got a hot date? An oil change appointment? Other things that are important but maybe not important to put in your google calendar?
        Put them here! Then you can open up your calendar and see what you got goin on, you ray of sunshine.
      </div>
    </div>
  </div>
</div>

app/views/meetings/index.html.erb
<%= month_calendar(attribute: :start_date, events: @meetings) do |date, meetings| %>
  <%= date %>
  <% meetings.each do |meeting| %>
    <div>
      <%= link_to meeting.title, meeting_path(meeting) %>
    </div>
  <% end %>
<% end %>

<%= link_to "Add a New Calendar Event", new_meeting_path %>

app/views/meetings/new.html.erb
<h2 class="ui centered header">New Calendar Event</h2>

<div class="ui container">
  <%= simple_form_for(@meeting, url: new_meeting_url, html: { class: "ui form" }) do |f| %>
    <div class="field">
      <%= f.input :title, placeholder: "Event Title" %>
    </div>
    <div class="field">
      <%= f.input :start_date, as: :date %>
    </div>
    <div class="field">
      <%= f.input :description %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Create Event", class: "positive ui button" %>
      <%= link_to "Cancel", my_calendar_path %>
    </div>
  <% end %>
</div>

app/views/meetings/show.html.erb
<%= render 'shared/show', item: @meeting %>