config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :dashboard, only: [:new, :create, :destroy]

  resources :meetings, only: [:show]

  resources :journals do
    resources :tags, module: :journals
  end

  resources :photos, except: [:index, :new, :create] do
    resources :tags, module: :photos
  end

  resources :agendas, except: [:index] do
    resources :tags, module: :agendas
  end

  get '/tag_search', to: 'tags#search'

  get '/my_dashboard', to: 'dashboards#show'

  get '/my_calendar', to: 'meetings#index'
  get '/new_meeting', to: 'meetings#new'
  post '/new_meeting', to: 'meetings#create'

  get '/my_photos', to: 'photos#index'
  get '/new_photo', to: 'photos#new'
  post '/new_photo', to: 'photos#create'

  get '/my_agendas', to: 'agendas#index'

  root 'static_pages#home'
end

app/models/agenda.rb
class Agenda < ApplicationRecord
  belongs_to :user
  has_rich_text :body
  has_many :tags, as: :taggable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def clean_tags
    self.tags.map(&:name).reject(&:nil?)[0].split(", ")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end
  
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  belongs_to :user
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
  has_many :tags, as: :taggable

  validates :title, :body, presence: true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user

  validates :title, :description, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :tags, as: :taggable
  has_one_attached :image

  validates :image, :summary, presence: true
  validates :image, content_type: { in: %w[image/jpeg, image/jpg, image/gif, image/png],
                                    message: "Must be a valid image type" },
                                    size: { less_than: 10.megabytes, message: "Must be 10mb or smaller" }
  validates :summary, length: { maximum: 150 }

  def show_image
    image.variant(resize_to_limit: [200, 200])
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :taggable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :build_dashboard

  has_many :journals, dependent: :destroy
  has_many :meetings, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :agendas, dependent: :destroy
  has_one :dashboard, dependent: :destroy

  private

    def build_dashbaord
      Dashbaord.create(user_id: self.id)
    end
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  before_action :find_agenda, except: [:index, :new, :create]

  def index
    @agendas = current_user.agendas.all
  end

  def new
    @agenda = current_user.agendas.build
  end

  def create
    @agenda = current_user.agendas.build(agenda_params)

    if @agenda.save
      flash[:notice] = "New agenda saved!"
      redirect_to @agenda
    else
      flash[:notice] = "Something went wrong"
      render :new
    end
  end

  def edit
  end

  def update
    @agenda.update(agenda_params)
    redirect_to agendas_path
  end

  def destroy
    @agenda.destroy
    flash[:notice] = "Agenda deleted"
    redirect_to my_agendas_path
  end

  private

    def find_agenda
      @agenda = Agenda.find(params[:id])
    end

    def agenda_params
      params.require(:agenda).permit(:title, :body, :tags)
    end

end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :find_journal, only: [:show, :edit, :update, :destroy]

  def index
    @journals = current_user.journals
  end

  def new
    @journal = current_user.journals.build
  end

  def create
    @journal = current_user.journals.build(journal_params)

    if @journal.save
      redirect_to @journal
      flash[:notice] = "Add tags to make this entry searchable!"
    else
      render 'new'
      flash[:notice] = "Something went wrong"
    end
  end


  def show
  end

  def edit
  end

  def update
    @journal.update(journal_params)
    redirect_to my_dashboard_path
  end


  def destroy
    @journal.destroy
    flash[:notice] = "Entry successfully deleted"
    redirect_to journals_path
  end

  private

    def find_journal
      @journal = Journal.find(params[:id])
    end

    def journal_params
      params.require(:journal).permit(:title, :body)
    end

    # def permitted_params
    #   params.require(:journal).permit(:title, :body, tags: [])
    # end
    #
    # def tags
    #   permitted_params.slice(:tags)
    # end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :find_meeting, only: [:show]

  def index
    @meetings = current_user.meetings
  end

  def new
    @meeting = current_user.meetings.build
  end

  def create
    @meeting = current_user.meetings.build(meeting_params)

    if @meeting.save
      flash[:notice] = "Event created!"
      redirect_to my_calendar_path
    else
      flash[:notice] = "Event not saved"
      redner :new
    end
  end

  def show
  end

  def destroy
    @meeting.destroy
    redirect_to my_calendar_path
  end

  private

   def meeting_params
     params.require(:meeting).permit(:title, :start_date, :description)
   end

   def find_meeting
     @meeting = Meeting.find(params[:id])
   end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :find_photo, except: [:index, :new, :create]

  def index
    @photos = current_user.photos
  end

  def new
    @photo = current_user.photos.build
  end

  def create
    @photo = current_user.photos.build(photo_params)
    @photo.image.attach(params[:photo][:image])

    if @photo.save
      flash[:notice] = "Add tags to make this entry searchable!"
      redirect_to @photo
    else
      flash[:notice] = "Something went wrong, please try again"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @photo.update(photo_params)
    redirect_to my_dashboard_path
  end

  def destroy
    @photo.destroy
    flash[:notice] = "Photo successfulyl removed"
    redirect_to my_photos_path
  end

  private

    def find_photo
      @photo = Photo.find(params[:id])
    end

    # def photo_params
    #   permitted_params.except(:tags)
    # end

    def photo_params
      params.require(:photo).permit(:title, :summary, :image, :tags)
    end

    # def tags
    #   permitted_params.slice(:tags)
    # end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def create
    @tag = @taggable.tags.new(tag_params)
    @tag.save
    redirect_to my_dashboard_path
    flash[:notice] = "Entry added!"
  end

  def search
    @results = Tag.all.includes(:taggable).select{ |x| x.name.include?(params[:tags][:tag]) }.map{ |x| x.taggable }
  end


  private

    def tag_params
      params.require(:tag).permit(:name)
    end

end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tc3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="ui container">
      <%= render 'shared/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_index.html.erb
<div class="ui stackable grid">
  <% items.each do |item| %>
    <div class="ui four wide column">
      <div class="ui card">
        <div class="content">
          <div class="centered header">
            <%if item.is_a?(Journal) %>
              <%= link_to item.title, journal_path(item) %>
            <% elsif item.is_a?(Photo) %>
              <%= link_to item.title, photo_path(item) %>
            <% else %>
              <%= link_to item.title, agenda_path(item) %>
            <% end %>
          </div>
        </div>
        <div class="content blurb"><%= (item.is_a?(Photo) ? image_tag(item.show_image) : item.body) %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<div class="ui huge stackable menu">
  <%= link_to "Time Capsule", root_path, class: "active item" %>
  <%= render 'shared/search' %>
  <div class="right menu">
    <% if !user_signed_in? %>
      <%= link_to "Sign In", new_user_session_path, class: "item right floated" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "item right floated" %>
    <% else %>
      <div class="ui right item">
        <%= link_to "My Dashboard", my_dashboard_path %>
      </div>
      <div class="ui dropdown right item">
        New Project
        <i class="dropdown icon"></i>
        <div class="menu">
          <div class="item"><%= link_to "Journal Entry", new_journal_path %></div>
          <div class="item"><%= link_to "Photo", new_photo_path %></div>
          <div class="item"><%= link_to "To-Do", new_agenda_path %></div>
          <div class="item"><%= link_to "View my Calendar", my_calendar_path %></div>
        </div>
      </div>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "item right floated" %>
    <% end %>
  </div>
</div>

app/views/shared/_search.html.erb
<%= simple_form_for(:tags, url: tag_search_path, method: :GET, html: { class: "search-form"}) do |f| %>
  <div class="ui category search">
    <div class="ui icon input search-input">
      <%= f.input :tag, placeholder: "Search entries by tag...", html: { class: "prompt" }, label: false %>
    </div>
  </div>
<% end %>

app/views/shared/_show.html.erb
<div class="ui segment">
  <p class="item-title"><strong><%= item.title %></strong></p>
  <hr>
  <p>
    <% if item.is_a?(Journal) %>
      <%= item.body %>
     <% elsif item.is_a?(Agenda) %>
      <%= item.body %>
    <% elsif item.is_a?(Meeting) %>
      <%= item.description %>
    <% else %>
      <%= image_tag item.image %>
      <p><%= item.summary %></p>
    <% end %>
  </p>
  <% unless item.is_a?(Meeting) %>
    <p>
      <small>Tags: <%= raw item.tags.map(&:name).join(", ") %></small>
    </p>
    <%= render 'tags/form', taggable: item %>
  <% end %>
  <%= link_to "Delete Entry", (item.is_a?(Journal) ? journal_path(item) :
                         item.is_a?(Photo) ? photo_path(item) :
                         item.is_a?(Meeting) ? meeting_path(item) : agenda_path(item)), method: :delete,
                         data: { confirm: "Are you sure?" }, class: "ui negative button delete-entry" %>
</div>

app/views/shared/_tags_form.html.erb
<%= simple_form_for([taggable, Tag.new]) do |f| %>
  <div class="field">
    <%= f.input :tags, collection: Journal::TAGS, input_html: { multipart: true, multiple: true } %>
  </div>
<% end %>