config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :dashboard, only: [:new, :create, :destroy]

  resources :meetings, only: [:show]

  resources :journals do
    resources :tags, module: :journals
  end

  resources :photos, except: [:index, :new, :create] do
    resources :tags, module: :photos
  end

  resources :agendas, except: [:index] do
    resources :tags, module: :agendas
  end

  get '/tag_search', to: 'tags#search'

  get '/my_dashboard', to: 'dashboards#show'

  get '/my_calendar', to: 'meetings#index'
  get '/new_meeting', to: 'meetings#new'
  post '/new_meeting', to: 'meetings#create'

  get '/my_photos', to: 'photos#index'
  get '/new_photo', to: 'photos#new'
  post '/new_photo', to: 'photos#create'

  get '/my_agendas', to: 'agendas#index'

  root 'static_pages#home'
end

app/models/agenda.rb
class Agenda < ApplicationRecord
  belongs_to :user
  has_rich_text :body
  has_many :tags, as: :taggable
end

app/controllers/agendas/tags_controller.rb
class Agendas::TagsController < TagsController
  before_action :set_taggable

  private

    def set_taggable
      @taggable = Agenda.find(params[:agenda_id])
    end

end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  before_action :find_agenda, except: [:index, :new, :create]

  def index
    @agendas = current_user.agendas.all
  end

  def new
    @agenda = current_user.agendas.build
  end

  def create
    @agenda = current_user.agendas.build(agenda_params)

    if @agenda.save
      flash[:notice] = "New agenda saved!"
      redirect_to @agenda
    else
      flash[:notice] = "Something went wrong"
      render :new
    end
  end

  def edit
  end

  def update
    @agenda.update(agenda_params)
    redirect_to agendas_path
  end

  def destroy
    @agenda.destroy
    flash[:notice] = "Agenda deleted"
    redirect_to my_agendas_path
  end

  private

    def find_agenda
      @agenda = Agenda.find(params[:id])
    end

    def agenda_params
      params.require(:agenda).permit(:title, :body, :tags)
    end

end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/views/agendas/index.html.erb
<%= render 'shared/index', items: @agendas %>

app/views/agendas/new.html.erb
<h2 class="ui centered header">Make a New Journal Entry</h2>

<div class="ui container">
  <%= simple_form_for(@agenda, local: true, html: { class: "ui form" }) do |f| %>
    <div class="field">
      <%= f.input :title, required: true %>
    </div>
    <div class="field journal-body">
      <%= f.label :body %>
      <%= f.rich_text_area :body, required: true %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Post Agenda", class: "positive ui button" %>
      <%= link_to "Cancel", my_dashboard_path %>
    </div>
  <% end %>
</div>

app/views/agendas/show.html.erb
<%= render 'shared/show', item: @agenda %>